server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: mongoadmin
      password: mongoadmin
      database: ms-account
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration